### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by ShixiangWang** [yufree/sciguide#8]
3.1.1 现代社会的形成 中的 这种分工导致的个体角色工具化或目的**话**经常给现代人带来困惑，话 应该为 化。

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/134907772-06fb995b-b757-4d81-8efe-1d1c1b94415c.png)

341 万多？

**Comment by yufree** [comment]
@ShixiangWang 感谢指出！已修改！ ed59807
