### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ShixiangWang** [yufree/sciguide#9]
![image](https://user-images.githubusercontent.com/25057508/140031983-3f1d6d67-7725-4eaf-a3ef-337678401241.png)

butterpoposter 多了 po

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/140032139-dd78aa92-e1f8-4e4a-b68f-86d3316636ab.png)

开方 应为 开放

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/140033882-0dbaf5e6-e82b-4180-abd3-259da1e0a4c0.png)

低薪？

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/140034141-99c540eb-7293-47ff-a3cb-a130cd0fd7fe.png)

篮球～

**Comment by yufree** [comment]
感谢！已修改 8e55baa

**Comment by ShixiangWang** [comment]
@yufree 不客气，我从书中学到很多东西。感谢开源分享。
